/**
 * Archivo editorial: árbol alternativo para explorar familias de formato sin revelar la jerarquía interna de Drive.
 * El modo Lite permite marcar ramas y consultar su compatibilidad sólo cuando se desea.
 */
import { useState } from "react";
import { ChevronDown, ChevronRight, Heart, TreePine } from "lucide-react";
import type { CatalogItem } from "@/data/catalog";
import { describeResource } from "@/data/catalogNarrative";

export function EditorialFormatTree({ groups, onOpen, favoriteBranches, onToggleBranchFavorite, tooltipsEnabled }: { groups: Array<[string, CatalogItem[]]>; onOpen: (item: CatalogItem) => void; favoriteBranches: string[]; onToggleBranchFavorite: (label: string) => void; tooltipsEnabled: boolean }) {
  const [expanded, setExpanded] = useState<string | null>(groups[0]?.[0] ?? null);
  return <section className="editorial-format-tree" aria-label="Árbol editorial de formatos"><header><div><span><TreePine size={15} />ÁRBOL EDITORIAL</span><h3>Formatos, familias y recursos.</h3><p>Una vista alternativa para orientarte por la familia de material antes de abrir una ficha o colección.</p></div><b>{groups.length} ramas</b></header><div className="editorial-tree-branches">{groups.map(([label, items], index) => { const favorite = favoriteBranches.includes(label); const tooltip = tooltipsEnabled ? `Compatibilidad de la rama ${label}: reúne ${items.length} recursos con usos y herramientas relacionados.` : undefined; return <article key={label} className={expanded === label ? "editorial-tree-branch editorial-tree-branch--open" : "editorial-tree-branch"}><div className="editorial-tree-branch-head"><button className="editorial-tree-branch-toggle" onClick={() => setExpanded(expanded === label ? null : label)} aria-expanded={expanded === label} title={tooltip}><span>RAMA {String(index + 1).padStart(2, "0")}</span><b>{label}</b><small>{items.length} recurso{items.length === 1 ? "" : "s"}</small><ChevronDown size={16} /></button><button className={favorite ? "editorial-branch-favorite editorial-branch-favorite--active" : "editorial-branch-favorite"} onClick={() => onToggleBranchFavorite(label)} aria-pressed={favorite} aria-label={favorite ? `Quitar ${label} de ramas favoritas` : `Agregar ${label} a ramas favoritas`} title={favorite ? "Quitar de ramas favoritas" : "Agregar a ramas favoritas"}><Heart size={15} fill={favorite ? "currentColor" : "none"} /></button></div>{expanded === label && <div>{items.slice(0, 6).map((item) => <button key={item.id} onClick={() => onOpen(item)} title={tooltipsEnabled ? `${describeResource(item).technical.apps.slice(0, 3).join(" · ")} · ${describeResource(item).technical.environment}` : undefined}><span>{item.isCollection ? "COLECCIÓN" : "ARCHIVO"}</span><b>{describeResource(item).clearTitle}</b><ChevronRight size={15} /></button>)}{items.length > 6 && <small>Abre un recurso para continuar explorando esta rama.</small>}</div>}</article>; })}</div></section>;
}
